version: '3.7'

services:

  # frontend:
  #   container_name: frontend-dev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3001:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #   stdin_open: true
  sut:
    build:
      context: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: run_tests.sh
